const appname = "MealMaven";
const appversion = "Version 1.0.0";
const credits = "@becem";
const email = "Email";

const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*****";
const forgotPassword = "Forgot Password";
const login = "Log in";
const signUp = "Sign up";
const createNewAccount = "or, create a new account ";
const loginWith = "Log in with";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Foulan";
const privacyPolicy = "Privacy Policy";
const termsAndCond = " Terms and Conditions";
const alreadyHaveAnAccount = "Already have an account ? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

const searchAnything = "Search Anything ...",
    todayDeal = "Today's deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Restaurant",
    topCategories = "Top Categories",
    pizza = "Pizza",
    burgers = "Burgers",
    sandwitch = "Sandwitch",
    desserts = "Desserts",
    salad = "Salad",
    featuredCategories = "Featured categories",
    loggedIn = "Logged in successfully",
    loggedOut = "Logged out successfully",
    oldpass = "Old password",
    newpass = "New password",
    allProducts = "All products";
