// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYl15PkZzeXJ42uVVk6ePBtlg5ASNTW0',
    appId: '1:856701090379:web:9477c39a702cdfb2736bce',
    messagingSenderId: '856701090379',
    projectId: 'foody-e5396',
    authDomain: 'foody-e5396.firebaseapp.com',
    storageBucket: 'foody-e5396.appspot.com',
    measurementId: 'G-4VVJRJ6224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpJvodrl-TCtv1IHN1p11Q-Tgc6kt7Arc',
    appId: '1:856701090379:android:2e8272743bd2814a736bce',
    messagingSenderId: '856701090379',
    projectId: 'foody-e5396',
    storageBucket: 'foody-e5396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5UpTEwLWpXwFnaZ6QVt-r0RKw_KhKAk',
    appId: '1:856701090379:ios:25ffeffb071d06f8736bce',
    messagingSenderId: '856701090379',
    projectId: 'foody-e5396',
    storageBucket: 'foody-e5396.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5UpTEwLWpXwFnaZ6QVt-r0RKw_KhKAk',
    appId: '1:856701090379:ios:6dbf1d655029cd87736bce',
    messagingSenderId: '856701090379',
    projectId: 'foody-e5396',
    storageBucket: 'foody-e5396.appspot.com',
    iosBundleId: 'com.example.foody.RunnerTests',
  );
}
